### ISSUE TITLE
Fragments again

### ISSUE THREAD

**Issue by pyromaniac** [detrohutt/babel-plugin-import-graphql#31]
Hey, sorry for being back but I found one issue: when you have a single file with several fragments and try to include it to, say, a query file, this way: `#import { frag1 } from "fragments.gql"`, it raises an error. If you do `#import "fragments.gql"`, it works as expected but it adds all the fragments at the end of the query.

**Comment by pyromaniac** [comment]
Oh wow, just realized that this is fine because my fragments are dependent on each other (included into each other) but I still believe it should not raise an error in the case of picking the fragments manually, it should load all the dependencies it needs

**Comment by detrohutt** [comment]
Hmm.. I don't think there is any official spec for me to reference for the `#import` syntax (I think `graphql-tag` may have invented that syntax), but I've never seen it have specifiers (default or named), it's always just the filename.

I'm still not sure I want to go inventing my own syntax and fragmenting the GraphQL ecosystem worse than it already is. I suppose I could add logic to parse the operations in a file to automatically determine and import whatever fragments are needed without actually introducing any new syntax.. but I'm not sure I want to incur the extra maintenance of the added complexity.

Additionally, the main change of the beta branch I've been working on is to utilize a builtin function from the `graphql` package called `separateOperations` which will replace my entire `multi-op.js` file. The more complexity I add, the less likely it's going to be viable to use `separateOperations`.

I'll have to think on this some. This plugin is downloaded almost 30k times per month and you're the first person to alert me to that particular use case, so there's apparently not very many people trying to do that, so I'm not sure it's worth the extra complexity to filter out the extra fragments. It may just need to be the cost of putting multiple fragments in one file.

I'll leave this open for now and come back to it once I've got `separateOperations` integrated to see how much trouble it'd be to add the "smart importing".

Thanks for bringing this to my attention.

**Comment by pyromaniac** [comment]
Btw, seems like `import { frag1 } from "fragments.gql"` works just fine in js files. That's why I was wondering.

**Comment by detrohutt** [comment]
I've decided the added complexity of "smart importing" is not worth the amount of benefit a few people would get from that feature. I want to keep the package as simple and stable as possible, especially now that I have very little time to work on it.

**Comment by pyromaniac** [comment]
okay
