### ISSUE TITLE
Is create-react-native-app supported?

### ISSUE THREAD

**Issue by pm-dev** [detrohutt/babel-plugin-import-graphql#34]
I'm attempting to use this plugin with a create-react-native-app (CRNA) but when importing a .graphql file into a typescript file, I'm seeing the error:
```
Unable to resolve ./query.graphql" from "src/Welcome/index.tsx`: The module `./query.graphql` could not be found.
```

I noticed the `babel-plugin-inline-import-graphql-ast` package, but it works with `react-app-rewired` which is for create-react-app and not create-react-native-app.

Any ideas?

Here's my .babelrc
```
{
  "plugins": ["import-graphql"],
  "presets": ["babel-preset-expo"],
  "env": {
    "development": {
      "plugins": [
        "transform-react-jsx-source"
      ]
    }
  }
}
```

and package.json
```
{
  "name": "tortuga",
  "version": "0.1.0",
  "private": true,
  "devDependencies": {
    "@types/jest": "^22.2.3",
    "@types/react": "^16.3.14",
    "@types/react-native": "^0.55.16",
    "@types/react-test-renderer": "^16.0.1",
    "apollo-codegen": "^0.19.1",
    "babel-plugin-import-graphql": "^2.4.4",
    "react-app-rewired": "^1.5.2",
    "react-native-scripts": "1.14.0",
    "react-native-typescript-transformer": "^1.2.9",
    "tslint-react": "^3.6.0",
    "typescript": "^2.8.3"
  },
  "main": "./src/index.js",
  "scripts": {
    "start": "react-native-scripts start",
    "eject": "react-native-scripts eject",
    "android": "react-native-scripts android",
    "ios": "react-native-scripts ios",
    "test": "jest",
    "generate-schema": "apollo-codegen introspect-schema http://localhost:8080/graphql --output lib/schema.json"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "apollo-boost": "^0.1.7",
    "expo": "^27.0.2",
    "graphql": "^0.13.2",
    "react": "16.4.0",
    "react-apollo": "^2.1.4",
    "react-native": "~0.55.2",
    "tslint": "^5.10.0"
  }
}
```

**Comment by detrohutt** [comment]
Hi @pm-dev , I've never actually used RN, but I went ahead and installed CRNA and created an app with it to test this out and it worked fine for me. I didn't set up a GraphQL server or anything, just followed these steps:

ran `yarn add -D babel-plugin-import-graphql`

ran `yarn add graphql`

added `"import-graphql"` to `.babelrc` plugins section

created a `query.graphql` file with this:

```graphql
query test {
  test
}
```

and added these two lines to their respective locations in the App.js file:

```javascript
import { test } from './query.graphql'

<Text>{query.kind}</Text>
```

It printed out `Document`, which means the file is being properly read and transformed into a GraphQL AST object, so it should work fine.

This package actually *is* `babel-plugin-inline-import-graphql-ast`, I've just changed the name a few days ago. I use it with `create-react-app` and created `react-app-rewire-inline-import-graphql-ast` as a shortcut to setting this package up with react-app-rewired.

Anyway, to answer your question, this does appear to support CRNA. My guess would be that you have a typo in your import statement, either the specifier (`{ query }`) or the path (`'./query.graphql'`).

Another possibility is that your using a more complicated document structure and making use of `NODE_PATH` or something.

Based on the error, it seems your file should be located at `src/Welcome/query.graphql`. Is that the case? And could you copy/paste your import statement?

**Comment by detrohutt** [comment]
@pm-dev Also, maybe update your version of CRNA?

**Comment by pm-dev** [comment]
@detrohutt Thanks for the quick response. I've confirmed that this library works with CRNA and it is only when importing into a typescript file, that the `Cannot find module` error happens. I've spent some time trying different tsconfig.json options, but no luck so far.

**Comment by detrohutt** [comment]
Oh it sounds like just a type issue. What i did was make a `types` folder in my project root with a `fileExtensions.d.ts` file like this in it:

```typescript
declare module '*.graphql';
```

And then add that folder to my `typeRoots` in `tsconfig.json`:

```json
"typeRoots": ["./types/", "./node_modules/@types/", "./**/node_modules/@types/"]
```

**Comment by pm-dev** [comment]
Changing the `module` compiler option in `tsconfig.json` from `commonjs` to `es2015` allowed the js bundle to build.

My IDE was still reporting an error because it couldn't find the module for my `.graphql` file, which was fixed by your suggestion of adding `fileExtensions.d.ts` with
```
declare module '*.graphql';
```

Thanks for your help debugging.

**Comment by darkbasic** [comment]
A better solution would be the following:
```ts
declare module '*.graphql' {
  const documentNode: import('graphql').DocumentNode;
  export default documentNode;
}
```

It has the advantage that the imported graphql queries will have the proper `DocumentNode` type set.
