### ISSUE TITLE
error: bundling failed

### ISSUE THREAD

**Issue by ovaris** [detrohutt/babel-plugin-import-graphql#35]
Hi,

I'm trying to use latest version of plugin (2.5.0) in react native project (babel-core 6.26.3) but I do get this error
```
error: bundling failed: TypeError: Cannot read property 'indexOf' of undefined
    at /xxx/node_modules/babel-plugin-import-graphql/build/index.js:46:22
```
here's my .babelrc
```
{
  "plugins": ["import-graphql"],
  "presets": ["react-native", "react-native-stage-0/decorator-support", "flow"]
}
```

Any ideas?

**Comment by detrohutt** [comment]
@ovaris `v2.5.1` was just published and should fix your issue! :)

**Comment by ovaris** [comment]
@detrohutt THX that was fast! I'm seeing now this, after upgrading:
```
ror: bundling failed: TypeError: Cannot read property 'options' of undefined
    at Plugin.manipulateOptions (xxx/node_modules/babel-plugin-import-graphql/build/index.js:49:32)
```

**Comment by detrohutt** [comment]
Alright. That *should* have fixed it, but I've got one more trick up my sleeve. Give me a few more minutes and I'll get another patch out.

**Comment by detrohutt** [comment]
Give `v2.5.2` a shot lol.

**Comment by ovaris** [comment]
Sleeve worked! Big thanks. Now only thing left to figure out is to how to get rid of Flow error:
`Cannot resolve module ./foo.graphql`

**Comment by detrohutt** [comment]
Aw, sorry, but I'm not going to be any help there. Never touched flow before. It *may* be something similar to the fix for a similar error in TypeScript that I shared [here](https://github.com/detrohutt/babel-plugin-import-graphql/issues/34#issuecomment-394462336). :man_shrugging:

**Comment by detrohutt** [comment]
Actually it looks like there are several ways to fix this for flow outlined [here](https://github.com/facebook/flow/issues/2852) :D

**Comment by detrohutt** [comment]
I'm going to close this issue. If you can't get the flow error fixed, you can open another issue for that and I'll try to find some time to see if there's something I can do on my end in the package code to fix that problem.

**Comment by ovaris** [comment]
Thx for support, Flow error was easy to fix, `.flowconfig`:
`module.name_mapper='.*\(.graphql\)' -> 'empty/object'`

**Comment by detrohutt** [comment]
Glad you got it working! Just let me know if you run into any more problems. And thanks for your patience while I got this issue taken care of.
