### ISSUE TITLE
Live reload with Expo / React Native

### ISSUE THREAD

**Issue by Almaju** [detrohutt/babel-plugin-import-graphql#44]
Hey, thanks for the great work!

I'm currently developing a React Native app but it feels quite painful having to clear the cache everytime I make a change (with "R" command in Expo console).

It would be awesome to have a livereload feature for development purpose. I tried with the runtime: true option in .babelrc but it does not seem to change the behavior.

**Comment by detrohutt** [comment]
I wish I could help but as I mentioned in #39 it's outside the scope of a plugin to offer that functionality. It's something babel would need to implement. Thanks for using my plugin!
