### ISSUE TITLE
How to watch the typeDefs file?

### ISSUE THREAD

**Issue by MoonTahoe** [detrohutt/babel-plugin-import-graphql#47]
This plugin doesn't register changes to the `typeDefs.graphql` file. I noticied that inside the documentation the suggestion is to delete the cache before starting:

> Each time you modify a GraphQL file, the node_modules/.cache/babel-loader folder must be cleared for the changes to take effect. I recommend prepending the relevant script in your package.json and rerunning the script when you change a GraphQL file:

>```json
> {
>  "scripts": {
>    "start": "rm -rf ./node_modules/.cache/babel-loader && node index.js"
>  }
>}
>```

The problem with this is what happens when you want to watch for changes and restart your server? 

```json
  "start": "nodemon --exec babel-node ./src -e js,graphql"
```

If I start my app using nodemon with babel-node to work fast and efficiently, changes to `typeDefs` will trigger a restart, but they don't show up in the schema because of the cache issue.

**Comment by detrohutt** [comment]
Possibly `"start": "nodemon --exec rm -rf ./node_modules/.cache/babel-loader && babel-node ./src -e js,graphql"`?

**Comment by MoonTahoe** [comment]
I don’t really like the idea of putting an ‘rm -rf... ‘ into an automated package.json script like that.

**Comment by detrohutt** [comment]
Sorry, I'm afraid that's the best I can do. As I mentioned [in issue 39](https://github.com/detrohutt/babel-plugin-import-graphql/issues/39) there's nothing I can do about this from inside a babel plugin. There's a link in that issue to an external discussion with more info.

**Comment by lorensr** [comment]
`rm -rf ./node_modules/.cache/babel-loader`

didn't work for me but this did:

`"dev": "nodemon -e js,graphql --exec 'rm -rf ./node_modules/.cache && babel-node src/index.js'"`
