### ISSUE TITLE
Usage with Babel 7

### ISSUE THREAD

**Issue by savovs** [detrohutt/babel-plugin-import-graphql#51]
Hi there, I'm trying to get the plugin to run with Babel 7, but no luck so far.

Here's what I tried;
`yarn add -D @babel/cli @babel/core @babel/preset-env babel-plugin-import-grapqhl`

```json
// .babelrc
{
  "presets": ["@babel/preset-env"],
  "plugins": ["import-grapqhl"]
}
```
When I run this command
`babel server/index.js`

I get this error:
`Cannot find module 'babel-plugin-import-grapqhl`

Have you guys tried using it with Babel 7?

Here's my dependencies:
```json
{
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "^7.2.3"
  }
}
```

**Comment by zippocage** [comment]
This should not be a problem with babel 7

You misspelled the plugin name. babel-plugin-import-grapqhl should be **babel-plugin-import-graphql**

Hopefully you found that out and this issue can be closed.

**Comment by savovs** [comment]
oh dear🤦‍♂️
