### ISSUE TITLE
Update to support graphql@14.x

### ISSUE THREAD

**Issue by JustFly1984** [detrohutt/babel-plugin-import-graphql#54]
npm WARN babel-plugin-import-graphql@2.6.2 requires a peer of graphql@>=0.9.6 but none is installed. You must install peer dependencies yourself.

**Comment by detrohutt** [comment]
The current version string supports that version. I just tested by installing In an empty directory immediately after `npm init`:
![image](https://puu.sh/CUzwA/204b5169a2.png)

**Comment by JustFly1984** [comment]
I'm using your plugin with aws-amplify and gatsby.js. Both of them require graphql at least 0.13.0, and some of the gatsby plugins require 14.1.1

**Comment by detrohutt** [comment]
There shouldn't be any issue installing whatever version of graphql you'd like. I installed the newest version in the screenshot above and got no warnings. Make sure you have actually installed the graphql package, because the warning may be indicating that it is not installed at all.

**Comment by JustFly1984** [comment]
@detrohutt Well, the thing is I can't install qraphql as direct dependency to my project, cos `gatsby.js` asks to do not install it separate.

**Comment by detrohutt** [comment]
I don’t use gatsby myself, but if that’s the case, I’m afraid there’s
nothing I can do to help. It wouldn’t make sense for me to bundle graphql
with this package.
